version: '3.8'
services:
  backend:
    networks:
      - crud-sample
    build: 
      context: ./app
    restart: always
    ports:
      - 2000:2000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=bassam
      - DB_PASSWORD=root
      - DB_NAME=trees
      - DB_PORT=3306
  frontend:
    build:
      context: ./client-crud
    networks:
      - crud-sample
    ports:
      - 8080:8080
networks:
  crud-sample:
    external: true
