version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=trees
      - MYSQL_USER=bassam
      - PORT=3306
    ports:
      - 3306:3306
    networks:
      - crud-sample
networks:
  crud-sample:
    external: true